name: brana
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  # speech_to_text: ^6.6.2
  # avatar_glow: ^3.0.1
  # clipboard: ^0.1.3
  # http: ^1.2.1
  # flutter_swiper_view: ^1.1.8
  # font_awesome_flutter: ^10.7.0
  # provider: ^6.1.2
  # lottie: ^3.1.2
  # flutter_pw_validator: ^1.6.0
  # model_viewer_plus: ^1.8.0
  # flutter_svg: ^2.0.10+1
  # google_nav_bar: ^5.0.6
  # connectivity_plus: ^6.0.3
  # internet_connection_checker: ^1.0.0+1
  # local_auth: ^2.2.0
  # youtube_player_flutter: ^8.1.2
  # flutter_email_sender: ^6.0.3
  # audioplayers: ^6.0.0
  # form_field_validator: ^1.1.0
  # cached_network_image: ^3.2.0
  # flutter_rating_bar: ^4.0.1
  # flutter_widget_from_html_core: ^0.15.1
  # animations: ^2.0.11
  # url_launcher: ^6.3.0
  curved_navigation_bar: ^1.0.6
  badges: ^3.1.2
  http: ^1.2.2
  equatable: ^2.0.5
  get_it: ^8.0.3          # Dependency injection
  dartz: ^0.10.1          # For Either error handling
  retrofit: ^4.0.0  
  freezed_annotation: 3.0.0
  json_annotation: ^4.9.0  
  dio: ^5.3.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: 3.0.4

flutter:


  uses-material-design: true

  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
